[package]
name = "wpilib-hal-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chipobject-rs = { path = "../lib" }
dlopen = "0.1.8"
dlopen_derive = "0.1.4"
rand = "0.8.5"
thiserror = "1.0.19"
